# Generated by Django 4.1.7 on 2024-01-21 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=20)),
                ('address_line_2', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=6)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('', ''), ('IT', 'IT'), ('Non IT', 'Non IT'), ('Govt', 'Goverment'), ('Institute', 'Institute')], max_length=100)),
                ('data', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrugGroup',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('prescription', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('prescription', models.CharField(max_length=200)),
                ('batch', models.CharField(max_length=100)),
                ('rac_no', models.CharField(max_length=100)),
                ('quantity', models.FloatField(max_length=5)),
                ('mrp', models.FloatField(max_length=20)),
                ('mfg_date', models.DateField(max_length=100)),
                ('exp_date', models.DateField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('drug_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.druggroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('', ''), ('Sr. Manager', 'Sr. Manager'), ('Manager', 'Manager'), ('Sr. Engineer', 'Sr. Engineer'), ('Asst. Engineer', 'Asst. Engineer'), ('Labour', 'Labour'), ('HR', 'HR'), ('Tester', 'Tester')], max_length=100)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=6)),
                ('date', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
