# Generated by Django 4.1.7 on 2023-03-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=15)),
                ("address_line_1", models.CharField(max_length=20)),
                ("address_line_2", models.CharField(max_length=20)),
                ("zip_code", models.IntegerField(max_length=6)),
                ("about", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("Non IT", "Non IT"),
                            ("Govt", "Goverment"),
                            ("Institute", "Institute"),
                        ],
                        max_length=100,
                    ),
                ),
                ("data", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
