# Generated by Django 4.1.7 on 2023-03-05 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("address_line_1", models.CharField(max_length=20)),
                ("address_line_2", models.CharField(max_length=20)),
                ("zip_code", models.CharField(max_length=6)),
                ("about", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("IT", "IT"),
                            ("Non IT", "Non IT"),
                            ("Govt", "Goverment"),
                            ("Institute", "Institute"),
                        ],
                        max_length=100,
                    ),
                ),
                ("data", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("Sr. Manager", "Sr. Manager"),
                            ("Manager", "Manager"),
                            ("Sr. Engineer", "Sr. Engineer"),
                            ("Asst. Engineer", "Asst. Engineer"),
                            ("Labour", "Labour"),
                            ("HR", "HR"),
                            ("Tester", "Tester"),
                        ],
                        max_length=100,
                    ),
                ),
                ("address_line_1", models.CharField(max_length=100)),
                ("address_line_2", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=6)),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "grade",
                    models.CharField(
                        choices=[("", ""), ("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=50,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.company"
                    ),
                ),
            ],
        ),
    ]
