# Generated by Django 4.1.7 on 2024-01-21 01:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='company',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='zip_code',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('dist', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
