# Generated by Django 4.1.7 on 2023-08-01 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugGroup',
            fields=[
                ('drugroup_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('prescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('prescription', models.CharField(max_length=200)),
                ('batch', models.CharField(max_length=100)),
                ('rac_no', models.CharField(max_length=100)),
                ('quantity', models.FloatField(max_length=5)),
                ('mrp', models.FloatField(max_length=20)),
                ('mfg_date', models.CharField(max_length=100)),
                ('exp_date', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('drug_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.druggroup')),
            ],
        ),
    ]
