# Generated by Django 4.1.7 on 2024-01-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_company_alter_product_drug_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='data',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
    ]
